-- MySQL Script generated by MySQL Workbench
-- qua 11 jun 2025 09:49:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modely
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modely` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `modely`;

-- -----------------------------------------------------
-- Table `tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `id_cliente` (`id_cliente` ASC),
  CONSTRAINT `tb_agendamento_ibfk_1`
    FOREIGN KEY (`id_cliente`) REFERENCES `tb_cliente` (`id_cliente`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `id_cliente` (`id_cliente` ASC),
  CONSTRAINT `tb_carrinho_ibfk_1`
    FOREIGN KEY (`id_cliente`) REFERENCES `tb_cliente` (`id_cliente`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `carga_horaria` TIME NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_funcionario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(100) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `cor` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `imagem` BLOB NOT NULL,
  PRIMARY KEY (`id_produto`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_vendas` (
  `id_vendas` INT NOT NULL AUTO_INCREMENT,
  `tb_cliente_id_cliente` INT NOT NULL,
  `tb_funcionario_id_funcionario` INT NOT NULL,
  `horario` TIME NOT NULL,
  `data` DATE NOT NULL,
  `comissao` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_vendas`),
  INDEX `tb_cliente_id_cliente` (`tb_cliente_id_cliente` ASC),
  INDEX `tb_funcionario_id_funcionario` (`tb_funcionario_id_funcionario` ASC),
  CONSTRAINT `tb_vendas_ibfk_1` FOREIGN KEY (`tb_cliente_id_cliente`) REFERENCES `tb_cliente` (`id_cliente`),
  CONSTRAINT `tb_vendas_ibfk_2` FOREIGN KEY (`tb_funcionario_id_funcionario`) REFERENCES `tb_funcionario` (`id_funcionario`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_itens_venda` (
  `tb_vendas_id_vendas` INT NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`tb_vendas_id_vendas`, `tb_produto_id_produto`),
  INDEX `fk_tb_vendas_has_tb_produto_tb_produto1_idx` (`tb_produto_id_produto` ASC),
  INDEX `fk_tb_vendas_has_tb_produto_tb_vendas1_idx` (`tb_vendas_id_vendas` ASC),
  CONSTRAINT `fk_tb_vendas_has_tb_produto_tb_vendas1`
    FOREIGN KEY (`tb_vendas_id_vendas`) REFERENCES `tb_vendas` (`id_vendas`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_vendas_has_tb_produto_tb_produto1`
    FOREIGN KEY (`tb_produto_id_produto`) REFERENCES `tb_produto` (`id_produto`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `tb_itens_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_itens_carrinho` (
  `tb_carrinho_id_carrinho` INT NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`tb_carrinho_id_carrinho`, `tb_produto_id_produto`),
  INDEX `fk_tb_carrinho_has_tb_produto_tb_produto1_idx` (`tb_produto_id_produto` ASC),
  INDEX `fk_tb_carrinho_has_tb_produto_tb_carrinho1_idx` (`tb_carrinho_id_carrinho` ASC),
  CONSTRAINT `fk_tb_carrinho_has_tb_produto_tb_carrinho1`
    FOREIGN KEY (`tb_carrinho_id_carrinho`) REFERENCES `tb_carrinho` (`id_carrinho`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carrinho_has_tb_produto_tb_produto1`
    FOREIGN KEY (`tb_produto_id_produto`) REFERENCES `tb_produto` (`id_produto`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

