-- MySQL Script generated by MySQL Workbench
-- Fri Apr 18 19:53:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema modely
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modely
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modely` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `modely` ;

-- -----------------------------------------------------
-- Table `modely`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `horario` TIME NULL DEFAULT NULL,
  `status` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `tb_agendamento_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `modely`.`tb_cliente` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `tb_carrinho_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `modely`.`tb_cliente` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL DEFAULT NULL,
  `material` VARCHAR(45) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `tamanho` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_carrinho_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_carrinho_item` (
  `id_carrinho` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_carrinho`, `id_produto`),
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `tb_carrinho_item_ibfk_1`
    FOREIGN KEY (`id_carrinho`)
    REFERENCES `modely`.`tb_carrinho` (`id_carrinho`),
  CONSTRAINT `tb_carrinho_item_ibfk_2`
    FOREIGN KEY (`id_produto`)
    REFERENCES `modely`.`tb_produto` (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_nascimento` VARCHAR(20) NULL DEFAULT NULL,
  `carga_horaria` VARCHAR(30) NULL DEFAULT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_vendas` (
  `id_vendas` INT NOT NULL AUTO_INCREMENT,
  `tb_cliente_id_cliente` INT NULL DEFAULT NULL,
  `tb_funcionario_id_funcionario` INT NULL DEFAULT NULL,
  `horario` VARCHAR(45) NULL DEFAULT NULL,
  `data` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vendas`),
  INDEX `tb_cliente_id_cliente` (`tb_cliente_id_cliente` ASC) VISIBLE,
  INDEX `tb_funcionario_id_funcionario` (`tb_funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `tb_vendas_ibfk_1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `modely`.`tb_cliente` (`id_cliente`),
  CONSTRAINT `tb_vendas_ibfk_2`
    FOREIGN KEY (`tb_funcionario_id_funcionario`)
    REFERENCES `modely`.`tb_funcionario` (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_item_venda` (
  `tb_vendas_id_vendas` INT NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tb_vendas_id_vendas`, `tb_produto_id_produto`),
  INDEX `tb_produto_id_produto` (`tb_produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `tb_item_venda_ibfk_1`
    FOREIGN KEY (`tb_vendas_id_vendas`)
    REFERENCES `modely`.`tb_vendas` (`id_vendas`),
  CONSTRAINT `tb_item_venda_ibfk_2`
    FOREIGN KEY (`tb_produto_id_produto`)
    REFERENCES `modely`.`tb_produto` (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modely`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modely`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(50) NULL DEFAULT NULL,
  `nome_usuario` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
